version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ott_postgres
    environment:
      POSTGRES_DB: ott_db
      POSTGRES_USER: ott_user
      POSTGRES_PASSWORD: ott_pass
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ott_user -d ott_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - ott_network

  nextjs_app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ott_nextjs_app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://ott_user:ott_pass@postgres:5432/ott_db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here
    volumes:
      - app_uploads:/app/data
      - ../data/posters:/app/data/posters
      - ../data/subtitles:/app/data/subtitles
      - ../data/videos:/app/data/videos
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ott_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  app_uploads:
    driver: local

networks:
  ott_network:
    driver: bridge